### ISSUE TITLE
3dsx version?

### ISSUE THREAD

**Issue by Macleykun** [DanTheMan827/TIKleaner#1]
Heya!

Wanted to thank you for making this handy program :) had 18 tickets that could be deleted!
Is it maybe possible to also make a 3dsx version?

**Comment by Macleykun** [comment]
[tikSweep.zip](https://github.com/DanTheMan827/tikSweep/files/7079307/tikSweep.zip)
heya, fiddelt around with getting it to compile and saw the 3dsx version come out aswell!
Here's the latest version in zip form, incase you wish to include it in a release.

also it seems that smdhtool and 3dsxtool have changed location from your build script.
it's now from 
/opt/devkitpro/devkitARM/bin/smdhtool & 3dsxtool
too
/opt/devkitpro/tools/bin/smdhtool & 3dsxtool

incase you wish to have a ci, i'll leave these notes for future me, or anyone else

git checkout/clone repo
 wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb
 sudo apt-get install gdebi-core
 sudo gdebi devkitpro-pacman.amd64.deb
 sudo pacman-key --recv BC26F752D25B92CE272E0F44F7FD5492264BB9D0 --keyserver keyserver.ubuntu.com
 dkp-pacman -Sl 3ds-dev 3ds-mpg123 3ds-libvorbisidec 3ds-opusfile 3ds-flac 3ds-wildmidi 3ds-jansson 3ds-pkg-config
wget https://github.com/Steveice10/bannertool/releases/download/1.2.0/bannertool.zip
unzip bannertool.zip
copy bin file to /bin/
repeat for:
https://github.com/dnasdw/3dstool/releases/download/v1.2.6/3dstool.zip
https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.17/makerom-v0.17-ubuntu_x86_64.zip
possibly chmod +X the bin files
compile.

thanks for making tiksweep! I have no clue how to correctly delete installed cia's, so i'm glad this exsits!

**Comment by DanTheMan827** [comment]
Sorry for the delayed response.

If you look inside [tikSweep.zip](https://github.com/DanTheMan827/tikSweep/releases/download/v1.1.2/tikSweep.zip) you'll find a 3dsx version of it as well as all of the other build output.

**Comment by Macleykun** [comment]
Heya Dan! I already compiled it for ya :) included it in my previous message! Perhaps you could add the .3dsx to your last release so others can easily download it aswell!

also, you want me to make a CI/CD for this or nah?

**Comment by Masamune3210** [comment]
There is already a 3dsx in the latest release zip

**Comment by Macleykun** [comment]
> There is already a 3dsx in the latest release zip

Ye, I only saw that just now. But if you use universal installer on the 3ds it would be handy to directly download the 3dsx version :p
